/// <reference types="cypress" />
import { faker } from '@faker-js/faker';

const telas = [[1280, 720], [768, 1024], [2340, 1080]]
telas.forEach((tela) => {
    describe("checkout "+tela, () => {    
        beforeEach(() => {
            cy.viewport(...tela)
            cy.visit("https://automationpratice.com.br/checkout-one")
        })

        it(`checkout com sucesso`, () => {
            cy.cadastro_firstname()
            cy.cadastro_lastname()
            cy.cadastro_companyname()
            cy.cadastro_email_usuario('gmail.com')
            cy.get('#country').select(2)
            cy.get('#city').select(2)
            cy.cadastro_cep()
            cy.cadastro_endereco()
            cy.anotacoes('testo pra teste testo pra teste')
            cy.salvar_dados()
            cy.salvarPreenchimento()
            cy.formaPagamento()
            cy.confirmarPedido()
            cy.verificarPedido('Order success!')
        })
        it(`checkout campos vazios`, () => {
            cy.salvar_dados()
            cy.salvarPreenchimento()
            cy.formaPagamento()
            cy.confirmarPedido()
            cy.VerificarErro('Preencha os dados de pagamento!')
        })
        it(`checkout campo Adress vazio`, () => {
            cy.cadastro_firstname()
            cy.cadastro_lastname()
            cy.cadastro_companyname()
            cy.cadastro_email_usuario('gmail.com')
            cy.SelectPais(2)
            cy.SelectCidade(2)
            cy.cadastro_cep()
            cy.anotacoes('testo pra teste testo pra teste')
            cy.salvar_dados()
            cy.salvarPreenchimento()
            cy.formaPagamento()
            cy.confirmarPedido()
            cy.ErroEndereco('O campo Address deve ser prenchido')
        })
        it(`checkout e-mail inválido`, () => {
            cy.cadastro_firstname()
            cy.cadastro_lastname()
            cy.cadastro_companyname()
            cy.cadastro_email_usuario('gmailcom')
            cy.SelectPais(2)
            cy.SelectCidade(2)
            cy.cadastro_cep()
            cy.cadastro_endereco()
            cy.anotacoes('testo pra teste testo pra teste')
            cy.salvar_dados()
            cy.salvarPreenchimento()
            cy.formaPagamento()
            cy.confirmarPedido()
            cy.ErroFirstName('O campo E-mail deve ser prenchido ou é inválido')
        })
        it(`checkout Zipcode vazio`, () => {
            cy.cadastro_firstname()
            cy.cadastro_lastname()
            cy.cadastro_companyname()
            cy.cadastro_email_usuario('gmail.com')
            cy.SelectPais(2)
            cy.SelectCidade(2)
            cy.cadastro_endereco()
            cy.anotacoes('testo pra teste testo pra teste')
            cy.salvar_dados()
            cy.salvarPreenchimento()
            cy.ErroFirstName('O campo Zip Code deve ser prenchido')
            cy.formaPagamento()
            cy.confirmarPedido()
        })
    })
})